# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from news.models import Story, Tourdate
from news.forms import StoryForm, TourdateForm
from django.contrib.auth.models import User 

def index(request):

    if request.method == "POST":
        print("Got form submission")
	form = StoryForm(request.POST)
	if form.is_valid:
            new_story = form.save()
	    return redirect(index)

	else:
	    print("Form has errors")
	    response = 'Errors:'
            print("Else loop is called")
	    form = StoryForm(request.POST)
	    for key in form.errors.keys():
                value = form.errors[key]
		errors = ''
		for error in value:
		    errors = errors + error + ' '
		    response = response + ' ' + key + ': ' + errors
	    return HttpResponse('<li class="error">' + response + '</li>')

    storyList = Story.objects.all().order_by('-date_posted')

    tourdateList = Tourdate.objects.all().order_by('-date')

    if storyList:
        print("storyList was generated by news.views")

    form = StoryForm()

    form2 = TourdateForm()

    context = {
            'story': storyList,
            'form': form,
            'form2': form2,
            'tourdate': tourdateList,

    }

    return render(request, 'news.html', context)

def addtourdate(request):

    if request.method == "POST":
        form = TourdateForm(request.POST)
        if form.is_valid:
            new_date = form.save()
            return redirect(index)
        else:
	    print("Form has errors")
	    response = 'Errors:'
            print("Else loop is called")
	    form = StoryForm(request.POST)
	    for key in form.errors.keys():
                value = form.errors[key]
		errors = ''
		for error in value:
		    errors = errors + error + ' '
		    response = response + ' ' + key + ': ' + errors
	    return HttpResponse('<li class="error">' + response + '</li>')
    return redirect(index)
